package br.com.paulopinheiro.jsimbaconv.view;

import br.com.paulopinheiro.jsimbaconv.control.SimbaConvService;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileFilter;

public class Jsimbaconv extends javax.swing.JFrame {
    private File chosenFile;

    public Jsimbaconv() {
        initComponents();
        setChosenFile(null);
    }

    private void setChosenFile(File chosenFile) {
        this.chosenFile = chosenFile;
        updateFilePathTB();
        updateConvertButton();
    }

    private void convertChosenFile() {
        try {
            SimbaConvService simbaService = new SimbaConvService(chosenFile);
        } catch (IOException ex) {
            Logger.getLogger(Jsimbaconv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateFilePathTB() {
        if (chosenFile==null) this.jtfZipFilePath.setText("");
        else jtfZipFilePath.setText(chosenFile.getAbsolutePath());
    }

    private void updateConvertButton() {
        if (chosenFile==null) {
            jbtConvert.setEnabled(false);
        } else jbtConvert.setEnabled(true);
    }

    private FileFilter getZipFileFilter() {
        FileFilter zipFileFilter;
        zipFileFilter = new FileFilter() {
            @Override
            public boolean accept(File file) {
                return (file.isDirectory()||file.getName().toLowerCase().endsWith(".zip"));
            }

            @Override
            public String getDescription() {
                return "Arquivos ZIP (.zip)";
            }
        };
        return zipFileFilter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcSearchZipFile = new javax.swing.JFileChooser();
        jbtBrowse = new javax.swing.JButton();
        jbtConvert = new javax.swing.JButton();
        jtfZipFilePath = new javax.swing.JTextField();

        jfcSearchZipFile.setFileFilter(getZipFileFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Converta arquivos do SIMBA para juntar no PJe");

        jbtBrowse.setText("Buscar");
        jbtBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBrowseActionPerformed(evt);
            }
        });

        jbtConvert.setText("Converter");
        jbtConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtBrowse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfZipFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtConvert)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtBrowse)
                    .addComponent(jbtConvert)
                    .addComponent(jtfZipFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBrowseActionPerformed
        int i=jfcSearchZipFile.showOpenDialog(null);
        if (i==1) setChosenFile(null);
        else setChosenFile(jfcSearchZipFile.getSelectedFile());
    }//GEN-LAST:event_jbtBrowseActionPerformed

    private void jbtConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConvertActionPerformed
        convertChosenFile();
    }//GEN-LAST:event_jbtConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jsimbaconv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jsimbaconv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jsimbaconv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jsimbaconv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jsimbaconv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtBrowse;
    private javax.swing.JButton jbtConvert;
    private javax.swing.JFileChooser jfcSearchZipFile;
    private javax.swing.JTextField jtfZipFilePath;
    // End of variables declaration//GEN-END:variables
}
